pages
lastPage
	^ HelpTopic
		title: 'The Jejak Trace framework - References'
		contents: 'REFERENCES

T. Goubier, ValMadeo Project Report: The Trace and Dynamic Program Analysis Framework, August 27, 2007, UBO Technical Report.

Goubier, T.; Dezan, C.; Pottier, B.; Jego, C.; , "Fine grain parallel decoding of turbo product codes: Algorithm and architecture," Turbo Codes and Related Topics, 2008 5th International Symposium on , vol., no., pp.90-95, 1-5 Sept. 2008. doi: 10.1109/TURBOCODING.2008.4658678
'