pages
introduction
	^ HelpTopic
		title: 'Introduction'
		contents:
'The Alternative System Browser

The AltBrowser, for short, is a replacement for the standard or improved system browser. Its aims are to present a powerfull, yet simple, view of your Smalltalk Image to explore and program with, trying a few innovations along the way (smart suggestions, git integration).

The AltBrowser is also, in itself, a work in progress on a framework for that type of GUI and that type of application in Pharo. Take it as a way to learn to write this type of code really well (both GUI and system integration), and to polish it.'
		